# render.yaml
# ملف Render Blueprint مصحح لمشروع Node.js مع PostgreSQL

services:
  # 1. خدمة قاعدة البيانات (PostgreSQL)
  - type: pserv
    name: restaurant-db
    # ملاحظة: خطة "free" متاحة وقد تكون كافية للتطوير
    # plan: standard 
    # autoDeploy: false # هذا الحقل غير صالح لـ pserv، يتم التحكم به من الواجهة
    
  # 2. خدمة الويب (Backend + Frontend)
  - type: web
    name: restaurant-app
    env: node
    # plan: standard # يمكنك البدء بالخطة المجانية ثم الترقية
    
    # أمر البناء: يتضمن تثبيت التبعيات ثم بناء المشروع
    buildCommand: "pnpm install && pnpm run build"
    
    # أمر التشغيل: تشغيل الخادم
    startCommand: "pnpm run start"
    
    # متغيرات البيئة
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: restaurant-db
          property: connectionString
      # يمكنك إضافة أي متغيرات أخرى هنا
      # - key: SECRET_KEY
      #   generateValue: true # Render يمكنه إنشاء قيمة عشوائية آمنة لك
