services:
  # 1. خدمة قاعدة البيانات (PostgreSQL) - بسيطة وبدون إعدادات بناء
  - type: pserv
    name: restaurant-db
    # لا تحتاج إلى أي حقول أخرى هنا، Render سيتكفل بالباقي
    # يمكنك تحديد إصدار postgres إذا أردت
    # postgresqlVersion: 15 

  # 2. خدمة الويب (Node.js)
  - type: web
    name: restaurant-app
    env: node # بيئة التشغيل هنا صحيحة
    
    # أمر البناء: تثبيت التبعيات ثم بناء المشروع
    buildCommand: "pnpm install && pnpm run build"
    
    # أمر التشغيل: تشغيل الخادم
    startCommand: "pnpm run start"
    
    # متغيرات البيئة
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: restaurant-db # اسم الخدمة التي أنشأناها أعلاه
          property: connectionString
      # - key: SECRET_KEY
      #   generateValue: true
